services:
  postgres:
    image: postgres:13.5
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=messagerie-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .               # dossier contenant votre Dockerfile et le code NestJS
      dockerfile: Dockerfile   # nom de votre Dockerfile
    container_name: messagerie_back_nest
    restart: always
    env_file:
      - .env                    # contient JWT_SECRET, DATABASE_URL, RABBITMQ_URL, etc.
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    ports:
      - "3000:3000"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres:
  rabbitmq-data:
  rabbitmq-log:
