# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres:13.5
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=messagerie-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432' 
  rabbitmq:
    build: .
    # image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq

  api:
    build: .
    container_name: messagerie_back_nest
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres:
  rabbitmq-data:
  rabbitmq-log:

