name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set dynamic tags
    - id: vars
      run: |
          TIMESTAMP=$(date +'%Y%m%d-%H%M')
          echo "TAG=$TIMESTAMP" >> $GITHUB_ENV
          echo "IMAGE_NAME=ghcr.io/efrei-message-app/messagerie-back-nest" >> $GITHUB_ENV
          echo "FULL_TAG=ghcr.io/efrei-message-app/messagerie-back-nest:$TIMESTAMP" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
    
    - name: Build the Docker image
      run: docker build -t $FULL_TAG -t $IMAGE_NAME:latest .

    - name: Push Docker image
      run: echo push step
